### ISSUE TITLE
审查规避策略

### ISSUE THREAD

**Issue by Pantyhose-X** [koalabearguo/php-proxy#2]
https://github.com/Kkevsterrr/geneva
https://github.com/BarbaTunnelCoder/BarbaTunnel/

**Comment by koalabearguo** [comment]
ok，长知识了，不过我这个工程基本用在免费的php server上的，一般都没有权限再安装软件了，这种类似tcp tunnel 的东西，就是数据再次封包，躲避审查的，真的用不上。。。
我这个东西只能走HTTPS和HTTP，当然这玩意可以自己装到自己的服务器上，但是一般不这样用，因为这个跟直接安装HTTPS PROXY，SSR，VPN等类似的代理性能可以差一倍。。。
我也找到一个伪装tcp/udp流量的，这个加速性能看起来x炸天
[https://github.com/esrrhs/pingtunnel](https://github.com/esrrhs/pingtunnel)
