### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by 362227** [koalabearguo/php-proxy#20]
弄了证书，但提示curl: (60) SSL certificate problem: EE certificate key too weak  能不能解决

**Comment by koalabearguo** [comment]
https://github.com/koalabearguo/php-proxy/blob/c95b84f7e6e0865f7971250e87e87c8e9a777a7a/casigner.go#L123
你可以自己编译go源码吗？把这里1024改成2048、3072或者4096，编译试一下，你curl对应系统的安全等级要求较高，需要长密钥

**Comment by 362227** [comment]
好 没问题

**Comment by 362227** [comment]
> https://github.com/koalabearguo/php-proxy/blob/c95b84f7e6e0865f7971250e87e87c8e9a777a7a/casigner.go#L123
> 
> 
> 你可以自己编译go源码吗？把这里1024改成2048、3072或者4096，编译试一下，你curl对应系统的安全等级要求较高，需要长密钥

curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

我用的是内置证书

**Comment by koalabearguo** [comment]
这证书是自签证书，需要加到你curl所在系统的信任列表里面，不然不受信任；如果是用的curl命令，可以加个-k参数。
