### ISSUE TITLE
自定义 UA

### ISSUE THREAD

**Issue by bclswl0827** [koalabearguo/php-proxy#4]
希望可以加入自定义 UA 功能，部分免费空间会检测 User-Agent 是否为浏览器，如果 User-Agent 不对劲会返回 403，比如 ByetHost

**Comment by koalabearguo** [comment]
OK，现在默认的UA是Go-http-client/1.*，后面加个自定义选项，同时把默认的UA改成请求端的UA

**Comment by koalabearguo** [comment]
已经修改好了，你可以把代码pull下来试下
windows平台下，编译go build命令就可以了
其他平台go build *.go
