### ISSUE TITLE
vercel使用问题

### ISSUE THREAD

**Issue by CTZZG** [koalabearguo/php-proxy#8]
[建议大佬最好取消vercel的推荐，因为vercel有官方声明](https://vercel.com/docs/concepts/limits/fair-use-policy)
Never Fair Use
❌ Proxies and VPNs
❌ Media hosting for hot-linking
❌ Scrapers
❌ Crypto Mining
❌ CPU-intensive APIs (e.g.: Machine Learning)
❌ Load Testing

**Comment by koalabearguo** [comment]
好吧，不过vercel速度是真的不错。

**Comment by CTZZG** [comment]
发现一个问题，windows编译运行报错panic: runtime error: invalid memory address or nil pointer dereference。
![image](https://user-images.githubusercontent.com/41315541/148866976-a4f6cf30-8f24-42d3-b9c6-e8e6751f5927.png)

**Comment by koalabearguo** [comment]
OK，我知道原因了，就是Body关闭的时候，需要判断是不是nil的

**Comment by koalabearguo** [comment]
我已经修复了，你可以更新到最新，自己编译一下，试试，不过正常情况下"fetchserver"配置如果确实可用，也不会有问题。

**Comment by CTZZG** [comment]
没问题了
